version: '3.7'

volumes:
    postgres:

services:
  postgres:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped

